vendor:
  208876:
    name:
     Aniket
    role:
     Debugger
  998987:
        name:
            Manikanta
        role:
            Developer

cvs:
  208876:
    name:
     Renuka
    role:
     Debugger
  998987:
        name:
            Priya
        role:
            Developer