vendor:
  383065:
    name:
     Kancharla, Venkat 
    role:
     Client Relationship Manager
  424844:
        name:
            Subramanian, Ranjith Ratna Kumar
        role:
            Engagement Manager 
  956801:
        name:
            Deshpande, Prafullata
        role:
            Sr Engineering Manager 
                      
   

cvs:
  218986:
    name:
     Shaik, Khadar B
    role:
     Sr Dir, Application Dvlp
  906457:
        name:
            Priya
        role:
            Developer